"""empty message

Revision ID: 032bc78ddbcc
Revises: 4a996e34aca5
Create Date: 2023-04-05 16:13:38.071253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032bc78ddbcc'
down_revision = '4a996e34aca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
