"""empty message

Revision ID: 52277fae5e20
Revises: 943f78f5a902
Create Date: 2023-04-10 19:55:56.754544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52277fae5e20'
down_revision = '943f78f5a902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
